cd /root/Bolsa/TomarDatosBolsa

echo "" > correo.txt

python test.py ABG  >> correo.txt
python test.py ABE >> correo.txt
python test.py ANA >> correo.txt
python test.py ACX >> correo.txt
python test.py ACS >> correo.txt
python test.py ADZ >> correo.txt
python test.py ADV >> correo.txt
python test.py AENA >> correo.txt
python test.py AIR >> correo.txt
python test.py ALNT >> correo.txt
python test.py ALM >> correo.txt
python test.py AMS >> correo.txt
python test.py AMP >> correo.txt
python test.py APAM >> correo.txt
python test.py APPS >> correo.txt
python test.py A3M >> correo.txt
python test.py CAF >> correo.txt
python test.py AXIA >> correo.txt
python test.py AZK >> correo.txt
python test.py SAB >> correo.txt
python test.py SAN >> correo.txt
python test.py BKIA >> correo.txt
python test.py BKT >> correo.txt
python test.py BDL >> correo.txt
python test.py CBAV >> correo.txt
python test.py BBVA >> correo.txt
python test.py BIO >> correo.txt
python test.py RIO >> correo.txt
python test.py BAIN >> correo.txt
python test.py CABK >> correo.txt
python test.py CAM >> correo.txt
python test.py CASH >> correo.txt
python test.py CLNX >> correo.txt
python test.py CIE >> correo.txt
python test.py CLEO >> correo.txt
python test.py CDR >> correo.txt
python test.py MDF >> correo.txt
python test.py OLE >> correo.txt
python test.py DIA >> correo.txt
python test.py DOGI >> correo.txt
python test.py EBRO >> correo.txt
python test.py EDR >> correo.txt
python test.py ENO >> correo.txt
python test.py ENG >> correo.txt
python test.py ENC >> correo.txt
python test.py ELE >> correo.txt
python test.py ECR >> correo.txt
python test.py EKT >> correo.txt
python test.py EZE >> correo.txt
python test.py FAE >> correo.txt
python test.py FCC >> correo.txt
python test.py FER >> correo.txt
python test.py FDR >> correo.txt
python test.py GAM >> correo.txt
python test.py GAS >> correo.txt
python test.py GEST >> correo.txt
python test.py GCO >> correo.txt
python test.py GRF >> correo.txt
python test.py GRF.P >> correo.txt
python test.py HIS >> correo.txt
python test.py IAG >> correo.txt
python test.py IBE >> correo.txt
python test.py IBG >> correo.txt
python test.py ITX >> correo.txt
python test.py IDR >> correo.txt
python test.py COL >> correo.txt
python test.py ISUR >> correo.txt
python test.py INY >> correo.txt
python test.py LBK >> correo.txt
python test.py LGT >> correo.txt
python test.py LOG >> correo.txt
python test.py MAP >> correo.txt
python test.py MAS >> correo.txt
python test.py TL5 >> correo.txt
python test.py MEL >> correo.txt
python test.py MRL >> correo.txt
python test.py MCM >> correo.txt
python test.py MTB >> correo.txt
python test.py NAT >> correo.txt
python test.py NTH >> correo.txt
python test.py HOME >> correo.txt
python test.py NHH >> correo.txt
python test.py NEA >> correo.txt
python test.py NYE >> correo.txt
python test.py OHL >> correo.txt
python test.py ORY >> correo.txt
python test.py PQR >> correo.txt
python test.py PHM >> correo.txt
python test.py PSG >> correo.txt
python test.py QBT >> correo.txt
python test.py RLIA >> correo.txt
python test.py RJF >> correo.txt
python test.py R4 >> correo.txt
python test.py REN >> correo.txt
python test.py REP >> correo.txt
python test.py REY >> correo.txt
python test.py ROVI >> correo.txt
python test.py SCYR >> correo.txt
python test.py SAY >> correo.txt
python test.py GSJ >> correo.txt
python test.py SGRE >> correo.txt
python test.py SNC >> correo.txt
python test.py SLR >> correo.txt
python test.py STG >> correo.txt
python test.py TLGO >> correo.txt
python test.py TRE >> correo.txt
python test.py TEF >> correo.txt
python test.py TPZ >> correo.txt
python test.py TUB >> correo.txt
python test.py TRG >> correo.txt
python test.py UNI >> correo.txt
python test.py VID >> correo.txt
python test.py VIS >> correo.txt
python test.py VOC >> correo.txt
python test.py ZOT >> correo.txt

python enviarCorreo.py


