python linearRegresion3.py ABG
python linearRegresion3.py ABE
python linearRegresion3.py ANA
python linearRegresion3.py ACX
python linearRegresion3.py ACS
python linearRegresion3.py ADZ
python linearRegresion3.py ADV
python linearRegresion3.py AENA
python linearRegresion3.py AIR
python linearRegresion3.py ALNT
python linearRegresion3.py ALM
python linearRegresion3.py AMS
python linearRegresion3.py AMP
python linearRegresion3.py APAM
python linearRegresion3.py APPS
python linearRegresion3.py A3M
python linearRegresion3.py CAF
python linearRegresion3.py AXIA
python linearRegresion3.py AZK
python linearRegresion3.py SAB
python linearRegresion3.py SAN
python linearRegresion3.py BKIA
python linearRegresion3.py BKT
python linearRegresion3.py BDL
python linearRegresion3.py CBAV
python linearRegresion3.py BBVA
python linearRegresion3.py BIO
python linearRegresion3.py RIO
python linearRegresion3.py BAIN
python linearRegresion3.py CABK
python linearRegresion3.py CAM
python linearRegresion3.py CASH
python linearRegresion3.py CLNX
python linearRegresion3.py CIE
python linearRegresion3.py CLEO
python linearRegresion3.py CDR
python linearRegresion3.py MDF
python linearRegresion3.py OLE
python linearRegresion3.py DIA
python linearRegresion3.py DOGI
python linearRegresion3.py EBRO
python linearRegresion3.py EDR
python linearRegresion3.py ENO
python linearRegresion3.py ENG
python linearRegresion3.py ENC
python linearRegresion3.py ELE
python linearRegresion3.py ECR
python linearRegresion3.py EKT
python linearRegresion3.py EZE
python linearRegresion3.py FAE
python linearRegresion3.py FCC
python linearRegresion3.py FER
python linearRegresion3.py FDR
python linearRegresion3.py GAM
python linearRegresion3.py GAS
python linearRegresion3.py GEST
python linearRegresion3.py GCO
python linearRegresion3.py GRF
python linearRegresion3.py GRF.P
python linearRegresion3.py HIS
python linearRegresion3.py IAG
python linearRegresion3.py IBE
python linearRegresion3.py IBG
python linearRegresion3.py ITX
python linearRegresion3.py IDR
python linearRegresion3.py COL
python linearRegresion3.py ISUR
python linearRegresion3.py INY
python linearRegresion3.py LBK
python linearRegresion3.py LGT
python linearRegresion3.py LOG
python linearRegresion3.py MAP
python linearRegresion3.py MAS
python linearRegresion3.py TL5
python linearRegresion3.py MEL
python linearRegresion3.py MRL
python linearRegresion3.py MCM
python linearRegresion3.py MTB
python linearRegresion3.py NAT
python linearRegresion3.py NTH
python linearRegresion3.py HOME
python linearRegresion3.py NHH
python linearRegresion3.py NEA
python linearRegresion3.py NYE
python linearRegresion3.py OHL
python linearRegresion3.py ORY
python linearRegresion3.py PQR
python linearRegresion3.py PHM
python linearRegresion3.py PSG
python linearRegresion3.py QBT
python linearRegresion3.py RLIA
python linearRegresion3.py RJF
python linearRegresion3.py R4
python linearRegresion3.py REN
python linearRegresion3.py REP
python linearRegresion3.py REY
python linearRegresion3.py ROVI
python linearRegresion3.py SCYR
python linearRegresion3.py SAY
python linearRegresion3.py GSJ
python linearRegresion3.py SGRE
python linearRegresion3.py SNC
python linearRegresion3.py SLR
python linearRegresion3.py STG
python linearRegresion3.py TLGO
python linearRegresion3.py TRE
python linearRegresion3.py TEF
python linearRegresion3.py TPZ
python linearRegresion3.py TUB
python linearRegresion3.py TRG
python linearRegresion3.py UNI
python linearRegresion3.py VID
python linearRegresion3.py VIS
python linearRegresion3.py VOC
python linearRegresion3.py ZOT
