echo "Ind,Ops,Dinero,Rent,Benef,BenefXOps,SalidaWin"
python test.py ANA
python test.py ACX
python test.py ACS
python test.py ADZ
python test.py ADV
python test.py AENA
python test.py AIR
python test.py ALNT
python test.py ALM
python test.py AMS
python test.py AMP
python test.py APAM
python test.py APPS
python test.py A3M
python test.py CAF
python test.py AXIA
python test.py AZK
python test.py SAB
python test.py SAN
python test.py BKIA
python test.py BKT
python test.py BDL
python test.py CBAV
python test.py BBVA
python test.py BIO
python test.py RIO
python test.py BAIN
python test.py CABK
python test.py CAM
python test.py CASH
python test.py CLNX
python test.py CIE
python test.py CLEO
python test.py DIA
python test.py DOGI
python test.py EBRO
python test.py EDR
python test.py ENO
python test.py ENG
python test.py ENC
python test.py ELE
python test.py ECR
python test.py EKT
python test.py EZE
python test.py FAE
python test.py FCC
python test.py FER
python test.py FDR
python test.py GAM
python test.py GAS
python test.py GEST
python test.py GCO
python test.py GRF
python test.py GRF.P
python test.py HIS
python test.py IAG
python test.py IBE
python test.py IBG
python test.py ITX
python test.py IDR
python test.py COL
python test.py ISUR
python test.py INY
python test.py LBK
python test.py LGT
python test.py LOG
python test.py MAP
python test.py MAS
python test.py TL5
python test.py MEL
python test.py MRL
python test.py MCM
python test.py MTB
python test.py NTH
python test.py HOME
python test.py NHH
python test.py NEA
python test.py NYE
python test.py OHL
python test.py ORY
python test.py PQR
python test.py PHM
python test.py PSG
python test.py RLIA
python test.py RJF
python test.py R4
python test.py REN
python test.py REP
python test.py REY
python test.py ROVI
python test.py SCYR
python test.py SAY
python test.py GSJ
python test.py SGRE
python test.py SNC
python test.py SLR
python test.py STG
python test.py TLGO
python test.py TRE
python test.py TEF
python test.py TPZ
python test.py TUB
python test.py TRG
python test.py UNI
python test.py VID
python test.py VIS
python test.py VOC
python test.py ZOT

 
